dw_user:
    resource: "@DWUserBundle/Resources/config/routing.yml"
    prefix:   /

dw_presentation:
    resource: "@DWPresentationBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
