parameters:
#    dw_presentation.example.class: DW\PresentationBundle\Example

services:
#    dw_presentation.example:
#        class: %dw_presentation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
